// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: setting.sql

package db

import (
	"context"
)

const createSetting = `-- name: CreateSetting :exec
insert into settings (account_id, relation_id, nick_name,  is_leader, is_self)
values (?,?,'',?,?)
`

type CreateSettingParams struct {
	AccountID  int64
	RelationID int64
	IsLeader   bool
	IsSelf     bool
}

func (q *Queries) CreateSetting(ctx context.Context, arg *CreateSettingParams) error {
	_, err := q.exec(ctx, q.createSettingStmt, createSetting,
		arg.AccountID,
		arg.RelationID,
		arg.IsLeader,
		arg.IsSelf,
	)
	return err
}
